version: 2
machine:
  python:
    version: 3.6.a
database:
  override:
    - mysql -u root circle_test < schema/start.sql
jobs:
  build:
    working_directory: ~/monica-python
    docker:
      - image: python:3.6.1
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=true
            MYSQL_HOST="%"
            MYSQL_USER=root
            MYSQL_PASSWORD=ubuntu
            MYSQL_DATABASE=circle_test
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python3 test_db/test.py
