version: 2
machine:
  python:
    version: 3.6.1
jobs:
  build:
    working_directory: ~/monica-python
    docker:
      - image: python:3.6.1
      - image: mysql:5.7
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: true
    steps:
      - checkout
      - run: apt-get update
      - run:
          name: Install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run: apt-get install -y libmysqlclient-dev mysql-client
      - run: dockerize -wait tcp://localhost:3305 -timeout 1m
      - run: mysql -u ubuntu circle_test < schema/start.sql
      - run: pip install -r requirements.txt
      - run: python3 test_db/test.py
