version: 2
machine:
  python:
    version: 3.6.1
database:
  override:
    - mysql -u ubuntu circle_test < schema/start.sql
jobs:
  build:
    working_directory: ~/monica-python
    docker:
      - image: python:3.6.1
      - image: mysql:5.7
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python3 test_db/test.py
