version: 2
machine:
  python:
    version: 3.6.1
jobs:
  build:
    working_directory: ~/monica-python
    docker:
      - image: circleci/python:3.6.1
      - image: circleci/mysql:5.7
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: true
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y libmysqlclient-dev mysql-client
      - run: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run: mysql -u ubuntu circle_test < schema/start.sql
      - run: pip install -r requirements.txt
      - run: python3 test_db/test.py
